apiVersion: v1
name: api-firewall
version: 0.7.2
appVersion: 0.8.9
description: Wallarm OpenAPI-based API Firewall
home: https://github.com/wallarm/api-firewall
icon: https://static.wallarm.com/wallarm-logo.svg
keywords:
  - wallarm
  - ingress
  - middleware
  - firewall
  - waf
sources:
  - https://github.com/wallarm/api-firewall
maintainers:
  - name: Wallarm Support Team
    email: support@wallarm.com
engine: gotpl
kubeVersion: ">=1.21.0-0"
